apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: us-central1-docker.pkg.dev/i-agility-465314-p6/backend/test-app:latest
          ports:
            - containerPort: 5000
          env:
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-configmap
                key: POSTGRES_USER
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-configmap
                key: POSTGRES_PASSWORD
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-configmap
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-configmap
                key: POSTGRES_DB
          # - name: DB_PORT
          #   valueFrom:
          #     configMapKeyRef:
          #       name: configmap
          #       key: DB_PORT
