apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  labels:
    app: app
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: mysecretpassword
  DB_HOST: postgres
  DB_PORT: "5432"