apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  # This is the key part that connects the PV to the disk created by Terraform.
  # The name must match the name of the disk created by `google_compute_disk`.
  gcePersistentDisk:
    pdName: app-data-disk
    fsType: ext4
  accessModes:
    # ReadWriteOnce means the volume can be mounted as read-write by a single Pod.
    - ReadWriteOnce
  capacity:
    # This size must match the size of the disk created in Terraform.
    storage: 10Gi
  # The "Retain" policy is crucial for data safety.
  # This ensures the underlying disk is NOT deleted when the PV or PVC is removed.
  persistentVolumeReclaimPolicy: Retain