apiVersion: v1
kind: PersistentVolume
metadata:
  # The PV name is now prefixed with the release name.
  name: {{ .Release.Name }}-postgres-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    # The storage capacity is now configurable.
    storage: {{ .Values.pvCapacity }}
  persistentVolumeReclaimPolicy: Retain
  # The PV now uses the configurable StorageClass name.
  storageClassName: {{ .Release.Name }}-storage-class