apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # The PVC name is now prefixed with the release name.
  name: {{ .Release.Name }}-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # The requested storage capacity is now configurable.
      storage: {{ .Values.pvcCapacity }}
  # The PVC now uses the configurable StorageClass name.
  storageClassName: {{ .Release.Name }}-storage-class