version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_HOST: db
      DB_NAME: postgres
      DB_PORT: 5432

