version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_HOST: db
      DB_NAME: postgres
      DB_PORT: 5432
  frontend:
    image: nginx:1.21
    restart: always
    volumes:
      - ./nginx-conf/index.html:/usr/share/nginx/html/index.html 
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf        
    ports:
      - "8000:80"
    depends_on:
      - backend
