name: Push to Artifact Registry

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: i-agility-465314-p6
  REPOSITORY: backend
  REGION: us-central1
  IMAGE_NAME: test-app
  TAG: latest   # or ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # required for WIF

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/225435158395/locations/global/workloadIdentityPools/github-actions-pool-v9/providers/github-actions-provider-v9'
          service_account: 'github-actions-v9@i-agility-465314-p6.iam.gserviceaccount.com'

      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 445.0.0'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

      # optional sanity check
      - name: Who am I?
        run: |
          gcloud auth list
          gcloud config list

      - name: Build Docker image
        run: |
          docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${TAG} docker-app/.

      - name: Push Docker image
        run: |
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${TAG}
