name: Push to Artifact Registry & Update Helm

on:
  push:
    branches: [ "main" ]
    # run only when app code changes (adjust as you like)
    paths:
      - 'docker-app/**'

env:
  PROJECT_ID: i-agility-465314-p6
  PROJECT_NUMBER: "225435158395"
  REGION: us-central1
  REPOSITORY: backend             # Artifact Registry repo name
  IMAGE_NAME: test-app              # image name
  TAG: ${{ github.sha }}            # immutable tag = commit SHA
  WIF_POOL_ID: github-actions-pool-v17
  WIF_PROVIDER_ID: github-actions-provider-v17
  SA_EMAIL: sgithub-actions-v17@i-agility-465314-p6.iam.gserviceaccount.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write    # REQUIRED for Workload Identity Federation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (Workload Identity Federation)
        uses: google-github-actions/auth@v2
        with:
          # IMPORTANT: provider path MUST use the PROJECT NUMBER, not project ID
          workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.WIF_POOL_ID }}/providers/${{ env.WIF_PROVIDER_ID }}'
          service_account: '${{ env.SA_EMAIL }}'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Verify auth (debug)
        run: |
          gcloud auth list
          gcloud artifacts repositories list --location ${{ env.REGION }}

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: |
          docker build \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
            docker-app

      - name: Push image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

  update-helm-chart:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write    # we commit back to the repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install yq
        uses: mikefarah/yq@v4.44.3

      - name: Update image repo & tag in values.yaml
        run: |
          # Update repo (host/repo/image) and tag
          yq -i '.image.repository = "'${{ env.REGION }}'-docker.pkg.dev/'${{ env.PROJECT_ID }}'/'${{ env.REPOSITORY }}'/'${{ env.IMAGE_NAME }}'"' k8s-app/values.yaml
          yq -i '.image.tag = "'${{ env.TAG }}'"' k8s-app/values.yaml

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add k8s-app/values.yaml
          git commit -m "ci: update image tag to ${{ env.TAG }}"
          git push
