name: Push to Artifact Registry

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: i-agility-465314-p6
  REPOSITORY: backend
  REGION: us-central1
  IMAGE_NAME: test-app
  TAG: latest   # or ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Authenticate to Google Cloud (WIF)
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/225435158395/locations/global/workloadIdentityPools/github-actions-pool-v9/providers/github-actions-provider-v9'
        service_account: 'github-actions-v9@i-agility-465314-p6.iam.gserviceaccount.com'
        # (no audience override)

    - name: Install gcloud
      uses: google-github-actions/setup-gcloud@v2

    # 🔑 Explicit docker login using a short-lived access token
    - name: Docker login to Artifact Registry
      run: |
        gcloud auth print-access-token | \
        docker login -u oauth2accesstoken --password-stdin https://${{ env.REGION }}-docker.pkg.dev

    - name: Build
      run: |
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} docker-app/.

    - name: Push
      run: |
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}}/${IMAGE_NAME}:${TAG}
